server:
  port: 8114
spring:
  application:
    name: acgt-api
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_tool?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: mysql
  zipkin:
      base-url: http://localhost:9411
  sleuth:
      sampler:
          probability: 1
          rate: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
feign:
  circuitbreaker: #open hystrix
    enabled: true

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

logging:
  level:
    com.work23.feign.UserDslFeign: debug


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.work23.entity
  global-config:
    db-config:
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false